// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(TMSContext))]
    [Migration("20250126155916_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.AppModels.Party", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyAddress")
                        .HasColumnType("nvarchar(125)");

                    b.Property<string>("CompanyContact")
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("CompanyEmail")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FocalPersonContact")
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("FocalPersonEmail")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FocalPersonName")
                        .HasColumnType("varchar(30)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRegisterd")
                        .HasColumnType("bit");

                    b.Property<string>("NTN")
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("STRNo")
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Party");
                });

            modelBuilder.Entity("Models.AppModels.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryFrom")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("GrossAmount")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NetAmount")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("PODate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PONo")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("PaymentMode")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ShipmentType")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TaxAmount")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TaxRate")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("VendorName")
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("PurchaseOrder");
                });

            modelBuilder.Entity("Models.AppModels.PurchaseOrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ItemName")
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("PurchaseOrderId")
                        .HasColumnType("int");

                    b.Property<string>("Qty")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Rate")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseOrderDetail");
                });

            modelBuilder.Entity("Models.AppModels.PurchaseOrderDetail", b =>
                {
                    b.HasOne("Models.AppModels.PurchaseOrder", null)
                        .WithMany("purchaseOrderDetail")
                        .HasForeignKey("PurchaseOrderId");
                });

            modelBuilder.Entity("Models.AppModels.PurchaseOrder", b =>
                {
                    b.Navigation("purchaseOrderDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
